apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-config
    labels:
        app: mkdocs-site
data:
    nginx.conf: |
        server {
          listen 8080;
          server_name _;
          
          location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html =404;
          }

          error_page 404 /404.html;
          location = /40x.html {
            root /usr/share/nginx/html;
          }

          # Prevent access to hidden files
          location ~ /\. {
            deny all;
          }

          # Additional security headers
          add_header X-Content-Type-Options nosniff;
          add_header X-Frame-Options SAMEORIGIN;
          add_header X-XSS-Protection "1; mode=block";
        }
